# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive RACE: directly copied from DM.RACE; adsl already starts as a copy of DM,
  # so RACE is already present. This block makes the mapping explicit and idempotent.
  adsl <- adsl |>
    mutate(RACE = sources$dm$RACE[match(USUBJID, sources$dm$USUBJID)])

  adsl
}

