# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # VISIT1DT: first visit date taken from SV where VISITNUM = 1, converted to a Date
  # (SAS date). One SV record per subject for VISITNUM = 1, so no ordering needed.
  adsl <- adsl |>
    derive_vars_merged(
      dataset_add = sources$sv,
      by_vars = vars(USUBJID),
      filter_add = VISITNUM == 1,
      new_vars = vars(VISIT1DT = convert_dtc_to_dt(SVSTDTC))
    )
  adsl
}

