# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive AVGDD: Avg Daily Dose (as planned) = CUMDOSE / TRTDURD
  # Both CUMDOSE and TRTDURD are assumed to have been derived in earlier steps of ADSL.
  # Guard against division by zero / missing TRTDURD.
  adsl <- adsl |>
    mutate(
      AVGDD = if_else(
        !is.na(CUMDOSE) & !is.na(TRTDURD) & TRTDURD > 0,
        CUMDOSE / TRTDURD,
        NA_real_
      )
    )
  adsl
}

