# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive DISCONFL: Y if the subject discontinued the study, i.e. the study
  # completion/discontinuation reason (DCREASCD) is anything other than
  # 'Completed'. Null otherwise. DCREASCD is derived earlier from DS, so it is
  # already available on adsl.
  adsl <- adsl |>
    mutate(
      DISCONFL = if_else(
        !is.na(DCREASCD) & DCREASCD != "Completed",
        "Y",
        NA_character_
      )
    )
  adsl
}

