# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # Derive SITEGR1: Pooled Site Group 1.
  # Per the spec: "refer to SAP, Section 7.1 - if not pooled then SITEGR1=SITEID.
  # If pooled, SITEGR1 will be 900". The SAP (not available here) defines which
  # sites are pooled. Since no pooling rule is provided in the specification or
  # in the source data, the safe, literal implementation is to default to the
  # non-pooled case: SITEGR1 = SITEID.
  adsl <- adsl |>
    mutate(
      SITEGR1 = SITEID
    )

  adsl
}

