# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive ETHNIC: carry DM.ETHNIC straight through into ADSL (a direct copy from
  # the SDTM DM domain on the same subject level, so no transformation is needed).
  # DM is the source dataset ADSL was built from, so ETHNIC already exists; we
  # still express this explicitly (merge/rename) in case ADSL did not carry it.
  adsl <- adsl |>
    derive_vars_merged(
      dataset_add = sources$dm,
      by_vars = vars(USUBJID),
      new_vars = vars(ETHNIC = ETHNIC)
    )

  adsl
}

