# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive TRT01A: Actual Treatment for Period 01.
  # Per the spec, TRT01A equals TRT01P: there is no difference between actual
  # and randomized treatment in this study. TRT01P is derived earlier in ADSL
  # (from DM.ARM), so we simply copy it across.
  adsl <- adsl |>
    mutate(TRT01A = TRT01P)

  adsl
}

