# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive AGEU: take Age Units directly from DM.AGEU (as per spec "DM.AGEU")
  adsl <- adsl |>
    mutate(AGEU = sources$dm$AGEU[match(USUBJID, sources$dm$USUBJID)])

  adsl
}

