# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive SUBJID: DM.SUBJID carried over directly into ADSL.
  # adsl is a copy of DM, so SUBJID is already present; re-assert it from
  # sources$dm as the explicit source of truth, preserving row order.
  adsl <- adsl |>
    mutate(SUBJID = sources$dm$SUBJID[match(USUBJID, sources$dm$USUBJID)])

  adsl
}

