# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # Derive COMP8FL: "Completers of Week 8 Population Flag"
  # Y if the subject has an SV record for VISITNUM = 8 AND ADSL ENDDT is on/after
  #   the date of that visit (SVSTDTC); N otherwise.
  # ENDDT is assumed to be derived earlier in ADSL (e.g. from RFENDTC/disposition);
  # SV.VISITNUM = 8 identifies the Week 8 visit.

  # Date of the Week 8 visit per subject, taken from the subject's SV records.
  # If a subject has more than one such record, use the earliest visit date.
  wk8 <- sources$sv |>
    filter(VISITNUM == 8) |>
    mutate(WK8DT = convert_dtc_to_dt(SVSTDTC)) |>
    group_by(USUBJID) |>
    summarise(WK8DT = min(WK8DT, na.rm = TRUE), .groups = "drop") |>
    # min() over an all-NA group returns Inf with a warning; reset to NA
    mutate(WK8DT = if_else(is.infinite(WK8DT), as.Date(NA), WK8DT))

  adsl <- adsl |>
    left_join(wk8, by = "USUBJID") |>
    mutate(
      COMP8FL = case_when(
        !is.na(WK8DT) & !is.na(ENDDT) & ENDDT >= WK8DT ~ "Y",
        TRUE ~ "N"
      )
    ) |>
    select(-WK8DT)

  adsl
}

