# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive EOSSTT: End of Study Status
  # DCDECOD is the standardized disposition term from the DS domain (last disposition
  # record). If it equals "COMPLETED", the subject completed the study; any other
  # (non-missing) disposition term means the subject discontinued.
  # We rely on ADSL.DCDECOD having been derived by an earlier step.
  adsl <- adsl |>
    mutate(
      EOSSTT = case_when(
        DCDECOD == "COMPLETED" ~ "COMPLETED",
        !is.na(DCDECOD)        ~ "DISCONTINUED",
        TRUE                   ~ NA_character_
      )
    )
  adsl
}

