# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # Derive DSRAEFL: "Y" if the subject's disposition reason code (DCREASCD) is
  # "Adverse Event", NA otherwise. DCREASCD is an ADSL variable derived earlier
  # in the ADSL build (from DS), so it is available on the incoming adsl.
  adsl <- adsl |>
    mutate(
      DSRAEFL = if_else(
        !is.na(DCREASCD) & DCREASCD == "Adverse Event",
        "Y",
        NA_character_
      )
    )
  adsl
}

