# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive AGE: per spec, simply carry DM.AGE through as an integer.
  # adsl already starts as a copy of DM, so AGE is present; we just ensure it is integer.
  adsl <- adsl |>
    mutate(AGE = as.integer(AGE))
  adsl
}

