# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive CUMDOSE: Cumulative Dose (as planned)
  #
  # For ARMN 0/1 (non-titration arms): CUMDOSE = TRT01PN * TRTDUR, i.e. planned
  #   daily dose (in mg units, taken from TRT01PN) multiplied by treatment duration.
  # For ARMN 2 (titration arm): dose escalates 54 -> 81 -> 54 mg/day across the
  #   1st (TRTSTDT..Visit 4), 2nd (Visit 4..Visit 12) and 3rd (Visit 12..TRTEDT)
  #   dosing intervals. The number of days in each interval is counted inclusive
  #   of the interval start day, using the subject's actual Visit 4 / Visit 12
  #   dates (from SV).
  #
  # ARMN and TRT01PN are derived earlier in ADSL; TRTSTDT/TRTEDT are the derived
  # treatment start/end dates.

  # 1. Subject-level Visit 4 and Visit 12 dates from SV ----------------------
  visit_dates <- sources$sv |>
    filter(VISIT %in% c("VISIT 4", "VISIT 12") | VISITNUM %in% c(4, 12)) |>
    mutate(
      # normalise whatever identifies the visit
      PARAM = case_when(
        VISITNUM == 4 | toupper(trimws(VISIT)) %in% c("VISIT 4", "WEEK 4", "VISIT4") ~ "V4",
        VISITNUM == 12 | toupper(trimws(VISIT)) %in% c("VISIT 12", "WEEK 12", "VISIT12") ~ "V12",
        TRUE ~ NA_character_
      )
    ) |>
    filter(!is.na(PARAM), !is.na(SVSTDTC)) |>
    mutate(SVSTDT = convert_dtc_to_dt(SVSTDTC))

  v4 <- visit_dates |>
    filter(PARAM == "V4", !is.na(SVSTDT)) |>
    arrange(USUBJID, SVSTDT) |>
    distinct(USUBJID, .keep_all = TRUE) |>
    select(USUBJID, V4DT = SVSTDT)

  v12 <- visit_dates |>
    filter(PARAM == "V12", !is.na(SVSTDT)) |>
    arrange(USUBJID, SVSTDT) |>
    distinct(USUBJID, .keep_all = TRUE) |>
    select(USUBJID, V12DT = SVSTDT)

  # 2. Merge visit dates into ADSL -------------------------------------------
  adsl <- adsl |>
    left_join(v4, by = "USUBJID") |>
    left_join(v12, by = "USUBJID")

  # 3. Compute CUMDOSE -------------------------------------------------------
  # helper: inclusive day count = end - start + 1
  adsl <- adsl |>
    mutate(
      # For arms 0/1: planned daily dose (TRT01PN) x treatment duration (TRTDUR)
      CUMDOSE_ARMN01 = TRT01PN * TRTDUR,
      # For arm 2: interval-based titration dosing
      CUMDOSE_ARMN2 = {
        start <- .data$TRTSTDT
        end   <- .data$TRTEDT
        v4d   <- .data$V4DT
        v12d  <- .data$V12DT

        # interval 1: TRTSTDT -> min(V4DT, TRTEDT); 54 mg/day
        i1_end  <- pmin(v4d, end, na.rm = TRUE)
        i1_days <- if_else(!is.na(i1_end) & !is.na(start), as.numeric(i1_end - start) + 1, 0)
        # if subject discontinued at/before V4 (no V4 date but end < planned), use end
        i1_days <- if_else(is.na(v4d) & !is.na(end) & !is.na(start),
                           as.numeric(end - start) + 1, i1_days)
        i1_days <- pmax(i1_days, 0)

        # interval 2: V4DT -> min(V12DT, TRTEDT); 81 mg/day (count days after V4)
        i2_end  <- pmin(v12d, end, na.rm = TRUE)
        i2_days <- if_else(!is.na(v4d) & !is.na(i2_end), as.numeric(i2_end - v4d), 0)
        # if discontinued after V4 but before/at V12 (no V12 date), use end - V4DT
        i2_days <- if_else(is.na(v12d) & !is.na(v4d) & !is.na(end),
                           as.numeric(end - v4d), i2_days)
        i2_days <- pmax(i2_days, 0)

        # interval 3: V12DT -> TRTEDT; 54 mg/day (count days after V12)
        i3_days <- if_else(!is.na(v12d) & !is.na(end), as.numeric(end - v12d), 0)
        i3_days <- pmax(i3_days, 0)

        i1_days * 54 + i2_days * 81 + i3_days * 54
      },
      CUMDOSE = case_when(
        ARMN %in% c(0, 1) ~ CUMDOSE_ARMN01,
        ARMN == 2          ~ CUMDOSE_ARMN2,
        TRUE               ~ NA_real_
      )
    ) |>
    select(-CUMDOSE_ARMN01, -CUMDOSE_ARMN2, -V4DT, -V12DT)

  adsl
}

