# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive SEX: copied directly from DM.SEX. adsl already starts as a copy of DM,
  # so SEX is carried over as-is; we only ensure the controlled terminology is applied.
  adsl <- adsl |>
    mutate(SEX = factor(SEX, levels = c("M", "F")))
  adsl
}

