# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive EDUCLVL: Years of Education, taken from SC.SCSTRESN where SC.SCTESTCD = "EDLEVEL".
  # One record per subject is expected; if multiple exist, take the first by SCSEQ.
  sc <- sources$sc

  edlevel <- sc |>
    filter(.data$SCTESTCD == "EDLEVEL") |>
    select(USUBJID, EDUCLVL = SCSTRESN, SCSEQ)

  adsl <- adsl |>
    derive_vars_merged(
      dataset_add = edlevel,
      by_vars = vars(USUBJID),
      order = vars(SCSEQ),
      mode = "first",
      new_vars = vars(EDUCLVL)
    ) |>
    # ensure integer type per specification
    mutate(EDUCLVL = as.integer(EDUCLVL))

  adsl
}

