# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # TRTDURD: Total Treatment Duration (Days) = TRTEDT - TRTSDT + 1
  # TRTSDT/TRTEDT are derived earlier in ADSL; guard against missing dates so the
  # arithmetic yields NA rather than an error.
  adsl |>
    mutate(
      TRTDURD = if_else(
        !is.na(TRTSDT) & !is.na(TRTEDT),
        as.integer(TRTEDT - TRTSDT + 1),
        NA_integer_
      )
    )
}

