# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # STUDYID: copied directly from DM.STUDYID; adsl already starts as a copy of DM,
  # so ensure the column is present (and re-copy from the source for safety).
  adsl <- adsl |>
    mutate(STUDYID = sources$dm$STUDYID[match(USUBJID, sources$dm$USUBJID)])
  adsl
}

