# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # WEIGHTBL: Baseline Weight (kg) taken from VS where VSTESTCD = "WEIGHT" and VISITNUM = 3.
  # Merge the single qualifying weight measurement per subject onto ADSL.
  vs <- sources$vs |>
    filter(VSTESTCD == "WEIGHT", VISITNUM == 3) |>
    select(USUBJID, WEIGHTBL = VSSTRESN)

  adsl |>
    derive_vars_merged(
      dataset_add = vs,
      by_vars     = vars(USUBJID)
    )
}

