# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive USUBJID: copied directly from DM.USUBJID. ADSL starts as a copy of DM,
  # so USUBJID is already present; re-assert it explicitly from the DM source to
  # guarantee the value regardless of any upstream modifications.
  adsl <- adsl |>
    left_join(
      sources$dm |> select(USUBJID),
      by = "USUBJID",
      relationship = "one-to-one"
    ) |>
    mutate(USUBJID = USUBJID)

  adsl
}

