# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive RFSTDTC: take the subject reference start date/time straight from DM.
  # DM is the source of adsl (adsl starts as a copy of DM), so RFSTDTC is
  # already present; this derivation simply ensures the column exists and is
  # character, matching the "DM.RFSTDTC" contract.
  adsl <- adsl |>
    mutate(RFSTDTC = as.character(RFSTDTC))
  adsl
}

