# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive ARM: planned arm description is taken directly from DM.ARM.
  # ADSL starts as a copy of DM, so ARM is already present; we simply ensure it
  # exists as a character variable carrying the DM.ARM values.
  adsl <- adsl |>
    mutate(ARM = as.character(ARM))
  adsl
}

