# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive DCDECOD: standardized disposition term from DS where DSCAT = 'DISPOSITION EVENT'
  # A subject can have multiple disposition event records; take the last one
  # (ordered by DSSTDTC / DSSEQ) so the final disposition status is captured.
  ds <- sources$ds

  ds_disp <- ds |>
    filter(DSCAT == "DISPOSITION EVENT", !is.na(DSDECOD)) |>
    # order by collection/start date then sequence to identify the last record
    arrange(USUBJID, DSSTDTC, DSSEQ)

  adsl <- adsl |>
    derive_vars_merged(
      dataset_add = ds_disp,
      by_vars = exprs(USUBJID),
      order = exprs(DSSTDTC, DSSEQ),
      mode = "last",
      new_vars = exprs(DCDECOD = DSDECOD)
    )

  adsl
}

