# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive BMIBLGR1: Pooled Baseline BMI Group 1
  # Categorise baseline BMI (BMIBL, derived earlier in ADSL) into pooled groups:
  #   "<25"   if BMIBL < 25
  #   "25-<30" if 25 <= BMIBL < 30
  #   ">=30"  if BMIBL >= 30
  # Subjects with missing BMIBL remain NA.
  adsl <- adsl |>
    mutate(
      BMIBLGR1 = case_when(
        !is.na(BMIBL) & BMIBL < 25 ~ "<25",
        !is.na(BMIBL) & BMIBL >= 25 & BMIBL < 30 ~ "25-<30",
        !is.na(BMIBL) & BMIBL >= 30 ~ ">=30",
        TRUE ~ NA_character_
      )
    )
  adsl
}

