# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # Derive RFENDTC: taken directly from DM.RFENDTC (no transformation required).
  # DM is already the basis of adsl, so RFENDTC may already be present; we
  # ensure it is carried over from the source DM dataset explicitly.
  adsl <- adsl |>
    mutate(RFENDTC = sources$dm$RFENDTC[match(USUBJID, sources$dm$USUBJID)])
  adsl
}

