# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # TRTEDT: Date of Last Exposure to Treatment.
  # Primary source: EX.EXENDTC on the subject's LAST EX record (latest treatment end).
  # Fallback: if the date of final dose is missing AND the subject discontinued after
  #   visit 3, use the discontinuation date (DS) as the date of last dose.

  # ---- Primary derivation: last EXENDTC date per subject ----
  # Take the record with the maximum EXENDTC (character ISO strings sort
  # chronologically for complete/consistent partial forms); convert to a Date.
  ex_last <- sources$ex |>
    filter(!is.na(EXENDTC)) |>
    arrange(USUBJID, EXENDTC) |>
    group_by(USUBJID) |>
    slice_tail(n = 1) |>
    ungroup() |>
    mutate(TRTEDT_EX = convert_dtc_to_dt(EXENDTC)) |>
    select(USUBJID, TRTEDT_EX)

  adsl <- adsl |>
    derive_vars_merged(
      dataset_add = ex_last,
      by_vars = vars(USUBJID),
      new_vars = vars(TRTEDT_EX)
    )

  # ---- Fallback source: discontinuation date from DS ----
  # "discontinued after visit 3" -> disposition events occurring after the visit 3
  # reference point. DS carries VISITNUM/VISIT; identify discontinuation records
  # (DSDECOD indicative of study discontinuation) occurring at/after visit 3.
  # Use the latest such DSSTDTC as the discontinuation date.
  ds_disc <- sources$ds |>
    filter(!is.na(DSSTDTC)) |>
    # Discontinuation-type disposition events: DSCAT / DSDECOD signal "DISCONTINUED"
    filter(
      grepl("DISCONT", toupper(coalesce(DSDECOD, ""))) |
        grepl("DISCONT", toupper(coalesce(DSTERM, "")))
    ) |>
    # after visit 3: VISITNUM strictly greater than 3 (or unknown visit but present)
    filter(is.na(VISITNUM) | VISITNUM > 3) |>
    arrange(USUBJID, DSSTDTC) |>
    group_by(USUBJID) |>
    slice_tail(n = 1) |>
    ungroup() |>
    mutate(TRTEDT_DS = convert_dtc_to_dt(DSSTDTC)) |>
    select(USUBJID, TRTEDT_DS)

  adsl <- adsl |>
    derive_vars_merged(
      dataset_add = ds_disc,
      by_vars = vars(USUBJID),
      new_vars = vars(TRTEDT_DS)
    )

  # ---- Combine: prefer EX date; fall back to DS date when EX is missing ----
  adsl <- adsl |>
    mutate(TRTEDT = coalesce(TRTEDT_EX, TRTEDT_DS)) |>
    select(-TRTEDT_EX, -TRTEDT_DS)

  adsl
}

