# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive AGEGR1N: pooled age group 1 (numeric)
  #   1 = AGE < 65
  #   2 = AGE 65-80 (inclusive of 65 and 80)
  #   3 = AGE > 80
  # AGE is the numeric age in DM (and hence in ADSL). Boundaries follow the
  # derivation text literally: 64 -> 1, 65 -> 2, 80 -> 2, 81 -> 3.
  adsl <- adsl |>
    dplyr::mutate(
      AGEGR1N = dplyr::case_when(
        AGE < 65 ~ 1,
        AGE >= 65 & AGE <= 80 ~ 2,
        AGE > 80 ~ 3
      )
    )
  adsl
}

