# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # Derive BMIBL: baseline BMI in kg/m^2 as WEIGHTBL / ((HEIGHTBL/100)^2).
  # WEIGHTBL (kg) and HEIGHTBL (cm) are expected to be present in adsl from earlier derivations.
  adsl <- adsl |>
    mutate(
      BMIBL = WEIGHTBL / ((HEIGHTBL / 100)^2)
    )
  adsl
}

