# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive DTHFL: "DM.DTHFL" - copy the death flag from SDTM DM onto ADSL.
  # DM is the source of ADSL's base columns already, but DM.DTHFL may not have
  # been carried over, so merge it explicitly by USUBJID.
  dm <- sources$dm

  adsl <- adsl |>
    derive_vars_merged(
      dataset_add = dm,
      by_vars = exprs(USUBJID),
      new_vars = exprs(DTHFL = DTHFL)
    )

  adsl
}

