# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive SITEID: copy directly from DM.SITEID (origin "derived" but value is
  # simply sourced from DM, which is already present in ADSL as a copy of DM).
  # adsl is initialised from DM, so SITEID should already be present; we make
  # this explicit and idempotent by re-deriving from DM keyed on USUBJID.
  adsl <- adsl |>
    select(-any_of("SITEID")) |>
    derive_vars_merged(
      dataset_add = sources$dm,
      by_vars = exprs(USUBJID),
      new_vars = exprs(SITEID = SITEID)
    )
  adsl
}

