# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # Derive TRTSDT: Date of First Exposure to Treatment
  # Spec: SV.SVSTDTC when SV.VISITNUM = 3, converted to SAS date.
  # Take the visit-3 record per subject (one record per subject in SV) and
  # parse SVSTDTC (ISO 8601) into a Date.
  adsl <- adsl |>
    derive_vars_merged(
      dataset_add = sources$sv,
      by_vars = vars(USUBJID),
      filter_add = VISITNUM == 3,
      new_vars = vars(TRTSDT = convert_dtc_to_dt(SVSTDTC))
    )
  adsl
}

