# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # VISNUMEN: End of Treatment Visit number.
  # If the disposition event "PROTCOL COMPLETED" occurred at DS.VISITNUM = 13,
  # map it to visit 12 (End of Treatment Visit); otherwise take the DS.VISITNUM
  # of the "PROTCOL COMPLETED" record.
  visnumen <- sources$ds |>
    filter(DSTERM == "PROTCOL COMPLETED") |>
    mutate(VISNUMEN = if_else(VISITNUM == 13, 12, VISITNUM)) |>
    # one record per subject; prefer the last recorded event if duplicates exist
    arrange(USUBJID, DSSEQ) |>
    group_by(USUBJID) |>
    summarise(VISNUMEN = last(VISNUMEN), .groups = "drop")

  adsl <- adsl |>
    left_join(visnumen, by = "USUBJID")

  adsl
}

