# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive SAFFL: Safety Population Flag
  # "Y" if ITTFL == "Y" and TRTSDT is not missing, otherwise "N".
  # ITTFL and TRTSDT are assumed to have been derived earlier in ADSL.
  adsl <- adsl |>
    mutate(
      SAFFL = if_else(
        !is.na(ITTFL) & ITTFL == "Y" & !is.na(TRTSDT),
        "Y",
        "N"
      )
    )
  adsl
}

