# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive ITTFL: Intent-To-Treat Population Flag
  # "Y" if ARMCD is not a blank/empty value, "N" otherwise.
  # Treat both NA and blank/whitespace-only ARMCD as "not treated" -> "N".
  adsl <- adsl |>
    dplyr::mutate(
      ITTFL = dplyr::if_else(
        !is.na(ARMCD) & trimws(ARMCD) != "",
        "Y",
        "N"
      )
    )
  adsl
}

