# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # Derive HEIGHTBL: baseline height in cm, taken from VS where VSTESTCD = 'HEIGHT'
  # and VISITNUM = 1. VSSTRESN is the numeric result in standard units (cm).
  # Merge one qualifying VS record per subject onto ADSL by USUBJID.
  height <- sources$vs |>
    filter(VSTESTCD == "HEIGHT", VISITNUM == 1) |>
    # In the (unexpected) case of multiple records per subject, keep the first
    # in sequence order for determinism.
    arrange(USUBJID, VSSEQ) |>
    distinct(USUBJID, .keep_all = TRUE) |>
    select(USUBJID, HEIGHTBL = VSSTRESN)

  adsl <- adsl |>
    left_join(height, by = "USUBJID")

  adsl
}

