# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive COMP16FL: Week 16 completers population flag.
  # "Y if subject has a SV.VISITNUM=10 and ENDDT>=date of visit 10, N otherwise".
  # ENDDT is the treatment end date on ADSL (derived previously). We take the
  # visit 10 date from SV (per subject), and flag subjects who attended the
  # visit 10 and whose treatment end date is on/after that visit date.

  # Visit 10 date per subject from SV (first record if duplicates exist)
  visit10 <- sources$sv |>
    filter(VISITNUM == 10) |>
    mutate(VISIT10DT = convert_dtc_to_dt(SVSTDTC)) |>
    select(USUBJID, VISIT10DT) |>
    distinct(USUBJID, .keep_all = TRUE)

  adsl <- adsl |>
    derive_vars_merged(
      dataset_add = visit10,
      by_vars = vars(USUBJID),
      new_vars = vars(VISIT10DT)
    )

  adsl <- adsl |>
    mutate(
      COMP16FL = case_when(
        # Has a visit 10 record and treatment end date is on/after that visit
        !is.na(VISIT10DT) & !is.na(ENDDT) & ENDDT >= VISIT10DT ~ "Y",
        TRUE ~ "N"
      )
    ) |>
    select(-VISIT10DT)

  adsl
}

