# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive TRT01P: Planned Treatment for Period 01 is taken directly from DM.ARM
  # (planned arm description). adsl is a copy of DM, so ARM is available.
  adsl <- adsl |>
    mutate(TRT01P = ARM)
  adsl
}

