# CONTROL ARM - free-form generation experiment. NOT package output. Do not ship.
# Generated by demo/automation/06_freeform_generate.R (DeepSeek, direct R code
# generation without the constrained-IR vocabulary). Executed only in the
# sandbox of 07_freeform_execute.R; see .agents/freeform-comparison-design.md.

derive <- function(adsl, sources) {
  # derive DURDSGR1: Pooled Disease Duration Group 1.
  # DURDIS (disease duration, in months) is derived earlier in the pipeline; subgroup
  # into "<12" (duration less than 12 months) and ">=12" (12 months or more).
  # DURDIS values that are missing remain NA (no assignment).
  adsl <- adsl |>
    mutate(
      DURDSGR1 = case_when(
        !is.na(DURDIS) & DURDIS <  12 ~ "<12",
        !is.na(DURDIS) & DURDIS >= 12 ~ ">=12",
        TRUE                          ~ NA_character_
      )
    )
  adsl
}

