old <- new.env(parent=globalenv())
for (f in list.files("admiralagent/audit/round3/before-src/R","[.]R$",full.names=TRUE)) sys.source(f, envir=old)
v <- old$new_variable_ir("ADSL","X",list(old$new_step("categorize",list(target="X",from="AGE",breaks=c(0,18,100),labels=c("Y","A"),right=matrix(TRUE)))))
cat("matrix before gate:",paste(old$validate_ir(list(v)),collapse=";"),"\n")
raw <- old$canonical_ir(list(v)); cat(raw,"\n")
cat("matrix before roundtrip:",tryCatch({x<-old$normalize_ir_records(jsonlite::fromJSON(raw,simplifyVector=FALSE));paste(old$validate_ir(x),collapse=";")},error=conditionMessage),"\n")
a <- list(old$new_variable_ir("ADSL","X",list(old$new_step("assign",list(target="X",from="AGE")))))
for (nm in c("order_variables","ir_dependency_report")) cat(nm,"bad known_columns:",tryCatch({old[[nm]](a,list());"ACCEPT"},error=conditionMessage),"\n")
spec <- old$mock_spec_adsl()[1,,drop=FALSE];spec$derivation<-list(c("A","B"))
cat("nested spec before:",tryCatch({old$classify_variables(spec,"ADSL");"ACCEPT"},error=conditionMessage),"\n")